// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BotInstance struct {
	ID        pgtype.UUID
	UserID    int64
	Name      string
	CreatedAt pgtype.Timestamptz
}

type BotSubscription struct {
	BotID     pgtype.UUID
	ChannelID string
}

type Channel struct {
	ChannelID  string
	EndpointID int64
}

type User struct {
	ID           pgtype.UUID
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	LastLogin    pgtype.Timestamptz
}
