// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BotInstance struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	CreatedAt  pgtype.Timestamptz
	TargetHook string
}

type BotSubscription struct {
	BotID     pgtype.UUID
	ChannelID string
}

type Channel struct {
	ChannelID  string
	EndpointID uuid.UUID
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	LastLogin    pgtype.Timestamptz
}
