// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuthData = `-- name: GetAuthData :one
SELECT username, password
FROM user_table
WHERE username LIKE $1 LIMIT 1
`

type GetAuthDataRow struct {
	Username pgtype.Text
	Password string
}

func (q *Queries) GetAuthData(ctx context.Context, username pgtype.Text) (GetAuthDataRow, error) {
	row := q.db.QueryRow(ctx, getAuthData, username)
	var i GetAuthDataRow
	err := row.Scan(&i.Username, &i.Password)
	return i, err
}

const getUserData = `-- name: GetUserData :one
SELECT username, mail, password, created_at , last_access
FROM user_table
WHERE username LIKE $1 LIMIT 1
`

type GetUserDataRow struct {
	Username   pgtype.Text
	Mail       pgtype.Text
	Password   string
	CreatedAt  pgtype.Timestamp
	LastAccess pgtype.Timestamp
}

func (q *Queries) GetUserData(ctx context.Context, username pgtype.Text) (GetUserDataRow, error) {
	row := q.db.QueryRow(ctx, getUserData, username)
	var i GetUserDataRow
	err := row.Scan(
		&i.Username,
		&i.Mail,
		&i.Password,
		&i.CreatedAt,
		&i.LastAccess,
	)
	return i, err
}
