// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BotTable struct {
	ID            pgtype.UUID
	OwnerID       pgtype.Int4
	Label         string
	WsUrl         string
	MentionRoleID string
}

type ChannelBotTag struct {
	ID        int32
	ChannelID pgtype.Text
}

type OnAir struct {
	VideoID       string
	PreviousState pgtype.Text
}

type RegChannel struct {
	ChannelID  string
	LastUpdate pgtype.Timestamp
	EndpointID string
}

type UserTable struct {
	ID         int32
	Username   pgtype.Text
	Mail       pgtype.Text
	Password   string
	CreatedAt  pgtype.Timestamp
	LastAccess pgtype.Timestamp
	MailToken  pgtype.Text
}
